// Code generated by "stringer -type GameStage ./cmd/galaxy-bot"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GamePending-0]
	_ = x[GameStarted-1]
	_ = x[GameFinished-2]
}

const _GameStage_name = "GamePendingGameStartedGameFinished"

var _GameStage_index = [...]uint8{0, 11, 22, 34}

func (i GameStage) String() string {
	if i < 0 || i >= GameStage(len(_GameStage_index)-1) {
		return "GameStage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameStage_name[_GameStage_index[i]:_GameStage_index[i+1]]
}
